name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # allow pushing

jobs:
  update-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "${{ secrets.COMMIT_NAME }}"
          git config user.email "${{ secrets.COMMIT_EMAIL }}"

      - name: Ensure log.txt exists
        run: |
          if [ ! -f log.txt ]; then
            echo "Creating log.txt"
            echo "==== Daily Log ====" > log.txt
          fi

      - name: Update log.txt
        run: |
          echo "$(date -u '+%Y-%m-%d'): DailyCommit" >> log.txt

      - name: Commit and push changes
        run: |
          git add log.txt
          git commit -m "Daily update: $(date -u '+%Y-%m-%d')" || echo "No changes to commit"
          git push
